# Generated by Django 2.2.7 on 2019-11-30 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageproduct', '0001_initial'),
    ]

    operations = [
    ]
